export const meatProducts = [
  {
    name: "Premium Beef",
    tag: "Beef",
    emoji: "🥩",
    desc: "Hand-cut steaks, T-bones, ribs and stew cuts from our farm-raised cattle.",
    img: "/img/p-beef-2.jpg",
    accent: "red",
    badge: "Best Seller",
  },
  {
    name: "Pork Chops & Ribs",
    tag: "Pork",
    emoji: "🐖",
    desc: "Whole carcasses (45–60kg) and freshly-cut pork chops, bacon and ribs.",
    img: "/img/p-pork-2.jpg",
    accent: "navy",
  },
  {
    name: "Goat Meat",
    tag: "Goat",
    emoji: "🐐",
    desc: "Lean, traditional goat meat — perfect for braais, stews and family dinners.",
    img: "/img/p-goat-cuts.jpg",
    accent: "red",
  },
  {
    name: "Fresh Chicken",
    tag: "Chicken",
    emoji: "🍗",
    desc: "Whole birds, mixed portions, wings and feet — fresh daily from local farms.",
    img: "/img/p-chicken.jpg",
    accent: "gold",
  },
  {
    name: "Fresh Fish",
    tag: "Fish",
    emoji: "🐟",
    desc: "Tilapia and bream — cleaned, sized and packed for your kitchen.",
    img: "/img/p-fish.jpg",
    accent: "navy",
  },
  {
    name: "Boerewors & Sausages",
    tag: "Sausages",
    emoji: "🌭",
    desc: "House-made boerewors and pork sausages, packed with traditional flavour.",
    img: "/img/p-sausages.jpg",
    accent: "red",
    badge: "Hot",
  },
  {
    name: "Mince & Burger Patties",
    tag: "Mince",
    emoji: "🍔",
    desc: "Freshly-ground beef mince and hand-pressed burger patties — grill-ready.",
    img: "/img/p-mince.jpg",
    accent: "red",
  },
  {
    name: "Bacon & Pork Belly",
    tag: "Bacon",
    emoji: "🥓",
    desc: "Streaky bacon, gammon steaks and rich pork belly cuts — sliced fresh.",
    img: "/img/p-pork.jpg",
    accent: "gold",
  },
  {
    name: "Polony",
    tag: "Polony",
    emoji: "🥪",
    desc: "Family-favourite polony — perfect for sandwiches, lunchboxes and snacks.",
    img: "/img/p-pork-3.jpg",
    accent: "navy",
  },
];

export const produceItems = [
  {
    name: "Tomatoes",
    img: "/img/v-tomatoes.jpg",
    color: "from-red-500 to-rose-600",
    emoji: "🍅",
  },
  {
    name: "Red Bell Peppers",
    img: "/img/v-peppers-red.jpg",
    color: "from-red-600 to-orange-600",
    emoji: "🫑",
  },
  {
    name: "Green Bell Peppers",
    img: "/img/v-peppers-green.jpg",
    color: "from-green-500 to-emerald-600",
    emoji: "🫑",
  },
  {
    name: "Mixed Peppers",
    img: "/img/v-peppers-mix.jpg",
    color: "from-yellow-400 to-green-500",
    emoji: "🌶️",
  },
  {
    name: "Carrots",
    img: "/img/v-carrots.jpg",
    color: "from-orange-500 to-amber-500",
    emoji: "🥕",
  },
  {
    name: "Onions",
    img: "/img/v-onions-yellow.jpg",
    color: "from-amber-400 to-yellow-600",
    emoji: "🧅",
  },
  {
    name: "Red Onions",
    img: "/img/v-onions-red.jpg",
    color: "from-rose-600 to-purple-700",
    emoji: "🧅",
  },
  {
    name: "Green Cabbage",
    img: "/img/v-cabbage.jpg",
    color: "from-lime-500 to-green-700",
    emoji: "🥬",
  },
  {
    name: "Red Cabbage",
    img: "/img/v-cabbage-red.jpg",
    color: "from-purple-600 to-pink-700",
    emoji: "🥬",
  },
  {
    name: "Broccoli",
    img: "/img/v-broccoli.jpg",
    color: "from-green-600 to-teal-700",
    emoji: "🥦",
  },
  {
    name: "Cucumbers",
    img: "/img/v-cucumber.jpg",
    color: "from-emerald-500 to-green-700",
    emoji: "🥒",
  },
  {
    name: "Zucchini",
    img: "/img/v-zucchini.jpg",
    color: "from-lime-500 to-emerald-700",
    emoji: "🥒",
  },
  {
    name: "Eggplant",
    img: "/img/v-eggplant.jpg",
    color: "from-purple-700 to-indigo-900",
    emoji: "🍆",
  },
  {
    name: "Farm Eggs",
    img: "/img/v-eggs.jpg",
    color: "from-amber-400 to-orange-500",
    emoji: "🥚",
  },
];

export const cattleGallery = [
  "/img/farm-cow.jpg",
  "/img/farm-cattle.jpg",
  "/img/farm-cattle-2.jpg",
  "/img/farm-cow-2.jpg",
  "/img/farm-cow-3.jpg",
  "/img/farm-cow-4.jpg",
  "/img/farm-cow-5.jpg",
  "/img/hero-bull-2.jpg",
];
